# Air Quality Dataset

In [5]:
import pandas as pd
%matplotlib inline
%pylab inline
import pprint

# To plot pretty figures
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12
plt.style.use('ggplot')
pylab.rcParams['figure.figsize'] = (20, 10)

Populating the interactive namespace from numpy and matplotlib

In [6]:
df = pd.read_csv('./AQdata_clean.csv')

In [7]:
df.columns

Index(['DateTime', 'idx', 'Date', 'Day', 'Hour', 'Weekday', 'Week', 'Month',
       'PT08.S1(CO)', 'PT08.S2(NMHC)', 'PT08.S3(NOx)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'CO(GT)', 'C6H6(GT)', 'NOx(GT)', 'NO2(GT)', 'T', 'RH',
       'AH', 'ewma'],
      dtype='object')

In [8]:
dailyMax = df.groupby('Date').max()
dailyMean = df.groupby('Date').mean()

In [ ]:
dailyMean['ewma'].plot.bar()

In [44]:
dailyMax.to_csv('AQdata_dailyMax.csv')
dailyMean.to_csv('AQdata_dailyMean.csv')

## Split into test and train set

In [47]:
df.set_index('DateTime')

,idx,Date,Day,Hour,Weekday,Week,Month,PT08.S1(CO),PT08.S2(NMHC),PT08.S3(NOx),PT08.S4(NO2),PT08.S5(O3),CO(GT),C6H6(GT),NOx(GT),NO2(GT),T,RH,AH
DateTime,,,,,,,,,,,,,,,,,,,
2004-03-10 18:00:00,0,2004-03-10,10,18,2,11,3,1360.0,1046.0,1056.0,1692.0,1268.0,2.6,11.9,166.0,113.0,13.6,48.9,0.7578
2004-03-10 19:00:00,1,2004-03-10,10,19,2,11,3,1292.0,955.0,1174.0,1559.0,972.0,2.0,9.4,103.0,92.0,13.3,47.7,0.7255
2004-03-10 20:00:00,2,2004-03-10,10,20,2,11,3,1402.0,939.0,1140.0,1555.0,1074.0,2.2,9.0,131.0,114.0,11.9,54.0,0.7502
2004-03-10 21:00:00,3,2004-03-10,10,21,2,11,3,1376.0,948.0,1092.0,1584.0,1203.0,2.2,9.2,172.0,122.0,11.0,60.0,0.7867
2004-03-10 22:00:00,4,2004-03-10,10,22,2,11,3,1272.0,836.0,1205.0,1490.0,1110.0,1.6,6.5,131.0,116.0,11.2,59.6,0.7888
2004-03-10 23:00:00,5,2004-03-10,10,23,2,11,3,1197.0,750.0,1337.0,1393.0,949.0,1.2,4.7,89.0,96.0,11.2,59.2,0.7848
2004-03-11 00:00:00,6,2004-03-11,11,0,3,11,3,1185.0,690.0,1462.0,1333.0,733.0,1.2,3.6,62.0,77.0,11.3,56.8,0.7603
2004-03-11 01:00:00,7,2004-03-11,11,1,3,11,3,1136.0,672.0,1453.0,1333.0,730.0,1.0,3.3,62.0,76.0,10.7,60.0,0.7702
2004-03-11 02:00:00,8,2004-03-11,11,2,3,11,3,1094.0,609.0,1579.0,1276.0,620.0,0.9,2.3,45.0,60.0,10.7,59.7,0.7648
2004-03-11 03:00:00,9,2004-03-11,11,3,3,11,3,1010.0,561.0,1705.0,1235.0,501.0,0.6,1.7,NaN,NaN,10.3,60.2,0.7517
2004-03-11 04:00:00,10,2004-03-11,11,4,3,11,3,1011.0,527.0,1818.0,1197.0,445.0,NaN,1.3,21.0,34.0,10.1,60.5,0.7465
2004-03-11 05:00:00,11,2004-03-11,11,5,3,11,3,1066.0,512.0,1918.0,1182.0,422.0,0.7,1.1,16.0,28.0,11.0,56.2,0.7366
2004-03-11 06:00:00,12,2004-03-11,11,6,3,11,3,1052.0,553.0,1738.0,1221.0,472.0,0.7,1.6,34.0,48.0,10.5,58.1,0.7353
2004-03-11 07:00:00,13,2004-03-11,11,7,3,11,3,1144.0,667.0,1490.0,1339.0,730.0,1.1,3.2,98.0,82.0,10.2,59.6,0.7417
2004-03-11 08:00:00,14,2004-03-11,11,8,3,11,3,1333.0,900.0,1136.0,1517.0,1102.0,2.0,8.0,174.0,112.0,10.8,57.4,0.7408
2004-03-11 09:00:00,15,2004-03-11,11,9,3,11,3,1351.0,960.0,1079.0,1583.0,1028.0,2.2,9.5,129.0,101.0,10.5,60.6,0.7691
2004-03-11 10:00:00,16,2004-03-11,11,10,3,11,3,1233.0,827.0,1218.0,1446.0,860.0,1.7,6.3,112.0,98.0,10.8,58.4,0.7552
2004-03-11 11:00:00,17,2004-03-11,11,11,3,11,3,1179.0,762.0,1328.0,1362.0,671.0,1.5,5.0,95.0,92.0,10.5,57.9,0.7352
2004-03-11 12:00:00,18,2004-03-11,11,12,3,11,3,1236.0,774.0,1301.0,1401.0,664.0,1.6,5.2,104.0,95.0,9.5,66.8,0.7951
2004-03-11 13:00:00,19,2004-03-11,11,13,3,11,3,1286.0,869.0,1162.0,1537.0,799.0,1.9,7.3,146.0,112.0,8.3,76.4,0.8393
2004-03-11 14:00:00,20,2004-03-11,11,14,3,11,3,1371.0,1034.0,983.0,1730.0,1037.0,2.9,11.5,207.0,128.0,8.0,81.1,0.8736
2004-03-11 15:00:00,21,2004-03-11,11,15,3,11,3,1310.0,933.0,1082.0,1647.0,946.0,2.2,8.8,184.0,126.0,8.3,79.8,0.8778
2004-03-11 16:00:00,22,2004-03-11,11,16,3,11,3,1292.0,912.0,1103.0,1591.0,957.0,2.2,8.3,193.0,131.0,9.7,71.2,0.8569
2004-03-11 17:00:00,23,2004-03-11,11,17,3,11,3,1383.0,1020.0,1008.0,1719.0,1104.0,2.9,11.2,243.0,135.0,9.8,67.6,0.8185
2004-03-11 18:00:00,24,2004-03-11,11,18,3,11,3,1581.0,1319.0,799.0,2083.0,1409.0,4.8,20.8,281.0,151.0,10.3,64.2,0.8065
2004-03-11 19:00:00,25,2004-03-11,11,19,3,11,3,1776.0,1488.0,702.0,2333.0,1704.0,6.9,27.4,383.0,172.0,9.7,69.3,0.8319
2004-03-11 20:00:00,26,2004-03-11,11,20,3,11,3,1640.0,1404.0,743.0,2191.0,1654.0,6.1,24.0,351.0,165.0,9.6,67.8,0.8133
2004-03-11 21:00:00,27,2004-03-11,11,21,3,11,3,1313.0,1076.0,957.0,1707.0,1285.0,3.9,12.8,240.0,136.0,9.1,64.0,0.7419
2004-03-11 22:00:00,28,2004-03-11,11,22,3,11,3,965.0,749.0,1325.0,1333.0,821.0,1.5,4.7,94.0,85.0,8.2,63.4,0.6905
2004-03-11 23:00:00,29,2004-03-11,11,23,3,11,3,913.0,629.0,1565.0,1252.0,552.0,1.0,2.6,47.0,53.0,8.2,60.8,0.6657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-04-03 09:00:00,9327,2005-04-03,3,9,6,13,4,1022.0,715.0,806.0,1004.0,831.0,1.2,4.1,192.0,118.0,17.8,30.7,0.6205
2005-04-03 10:00:00,9328,2005-04-03,3,10,6,13,4,970.0,677.0,888.0,931.0,613.0,1.4,3.4,166.0,113.0,21.1,23.7,0.5875
2005-04-03 11:00:00,9329,2005-04-03,3,11,6,13,4,1000.0,779.0,805.0,1001.0,640.0,1.3,5.3,171.0,115.0,24.0,19.3,0.5673
2005-04-03 12:00:00,9330,2005-04-03,3,12,6,13,4,996.0,781.0,806.0,985.0,631.0,1.4,5.3,177.0,124.0,26.5,16.4,0.5594
2005-04-03 13:00:00,9331,2005-04-03,3,13,6,13,4,928.0,701.0,926.0,902.0,456.0,1.0,3.8,119.0,86.0,28.7,13.7,0.5302
2005-04-03 14:00:00,9332,2005-04-03,3,14,6,13,4,933.0,722.0,899.0,890.0,450.0,1.0,4.2,121.0,87.0,28.5,13.1,0.5002
2005-04-03 15:00:00,9333,2005-04-03,3,15,6,13,4,956.0,783.0,857.0,896.0,516.0,1.1,5.4,142.0,100.0,30.0,11.1,0.4624
2005-04-03 16:00:00,9334,2005-04-03,3,16,6,13,4,968.0,826.0,867.0,898.0,548.0,1.3,6.3,197.0,132.0,29.4,10.4,0.4192
2005-04-03 17:00:00,9335,2005-04-03,3,17,6,13,4,953.0,817.0,872.0,891.0,603.0,1.4,6.1,242.0,156.0,28.9,9.9,0.3866
2005-04-03 18:00:00,9336,2005-04-03,3,18,6,13,4,1015.0,743.0,851.0,981.0,597.0,1.2,4.6,190.0,138.0,22.8,21.7,0.5945
2005-04-03 19:00:00,9337,2005-04-03,3,19,6,13,4,1248.0,1018.0,599.0,1289.0,1167.0,2.7,11.1,367.0,181.0,19.9,33.0,0.7608
2005-04-03 20:00:00,9338,2005-04-03,3,20,6,13,4,1180.0,894.0,636.0,1200.0,1372.0,2.5,7.9,355.0,187.0,17.5,40.7,0.8073
2005-04-03 21:00:00,9339,2005-04-03,3,21,6,13,4,1102.0,812.0,693.0,1178.0,1042.0,1.5,6.0,235.0,158.0,16.4,46.6,0.8642
2005-04-03 22:00:00,9340,2005-04-03,3,22,6,13,4,1116.0,803.0,696.0,1173.0,1055.0,1.6,5.8,233.0,153.0,15.5,49.0,0.8579
2005-04-03 23:00:00,9341,2005-04-03,3,23,6,13,4,1100.0,769.0,722.0,1147.0,1049.0,1.2,5.1,170.0,128.0,14.3,52.5,0.8497
2005-04-04 00:00:00,9342,2005-04-04,4,0,0,14,4,1012.0,683.0,801.0,1073.0,816.0,0.9,3.5,117.0,93.0,14.2,51.4,0.8275
2005-04-04 01:00:00,9343,2005-04-04,4,1,0,14,4,944.0,579.0,925.0,1002.0,598.0,0.6,1.9,70.0,58.0,13.8,51.2,0.8058
2005-04-04 02:00:00,9344,2005-04-04,4,2,0,14,4,912.0,544.0,959.0,1002.0,573.0,0.5,1.5,69.0,55.0,12.1,56.3,0.7927
2005-04-04 03:00:00,9345,2005-04-04,4,3,0,14,4,887.0,508.0,1047.0,974.0,549.0,0.4,1.1,62.0,51.0,11.3,58.9,0.7888
2005-04-04 04:00:00,9346,2005-04-04,4,4,0,14,4,864.0,478.0,1116.0,958.0,489.0,NaN,0.8,52.0,43.0,11.8,56.0,0.7743
2005-04-04 05:00:00,9347,2005-04-04,4,5,0,14,4,888.0,528.0,1077.0,987.0,578.0,0.5,1.3,77.0,53.0,10.4,59.9,0.7550
2005-04-04 06:00:00,9348,2005-04-04,4,6,0,14,4,1031.0,730.0,760.0,1129.0,905.0,1.1,4.4,182.0,93.0,9.5,63.1,0.7531
2005-04-04 07:00:00,9349,2005-04-04,4,7,0,14,4,1384.0,1221.0,470.0,1600.0,1457.0,4.0,17.4,594.0,155.0,9.7,61.9,0.7446
2005-04-04 08:00:00,9350,2005-04-04,4,8,0,14,4,1446.0,1362.0,415.0,1777.0,1705.0,5.0,22.4,586.0,174.0,13.5,48.9,0.7553
2005-04-04 09:00:00,9351,2005-04-04,4,9,0,14,4,1297.0,1102.0,507.0,1375.0,1583.0,3.9,13.6,523.0,187.0,18.2,36.3,0.7487
2005-04-04 10:00:00,9352,2005-04-04,4,10,0,14,4,1314.0,1101.0,539.0,1374.0,1729.0,3.1,13.5,472.0,190.0,21.9,29.3,0.7568
2005-04-04 11:00:00,9353,2005-04-04,4,11,0,14,4,1163.0,1027.0,604.0,1264.0,1269.0,2.4,11.4,353.0,179.0,24.3,23.7,0.7119
2005-04-04 12:00:00,9354,2005-04-04,4,12,0,14,4,1142.0,1063.0,603.0,1241.0,1092.0,2.4,12.4,293.0,175.0,26.9,18.3,0.6406
2005-04-04 13:00:00,9355,2005-04-04,4,13,0,14,4,1003.0,961.0,702.0,1041.0,770.0,2.1,9.5,235.0,156.0,28.3,13.5,0.5139
2005-04-04 14:00:00,9356,2005-04-04,4,14,0,14,4,1071.0,1047.0,654.0,1129.0,816.0,2.2,11.9,265.0,168.0,28.5,13.1,0.5028

In [55]:
24*340

8160

In [51]:
# df_with_dummies = pd.get_dummies( df, columns = ['Weekday'])

In [56]:
year_data = df[:24*340]
test_data = df[24*340:]
train_data.to_csv('train8160.csv')
test_data.to_csv('test1197.csv')